### ISSUE TITLE
A question about koniq-10k and bid dataset

### ISSUE THREAD

**Issue by feng150416** [SSL92/hyperIQA#6]
Thanks for releasing your code！but I have a question about koniq-10k and bid dataset。In data_loader.py，why would you resize the image size to (512,384) for koniq-10k dataset and resize the image size to (512,512) for bid dataset?

**Comment by SSL92** [comment]
For Koniq-10k dataset, we just follow the same resizing operation from the origin paper [https://arxiv.org/pdf/1910.06180v1.pdf](url). As for BID dataset, since images in this dataset cover a wide range of resolutions, so resizing them to the same scale makes our model to better capture the content information. Actually, we didn't purposely choose 512x512 as the best scale, you can also resize them to other scales to see if the performance has further improvement.

**Comment by feng150416** [comment]
Thanks for your replying！I got it
